public enum Instruments {
    public static let all: [Registration] = [
        .reading(MemoryFootprint.self),
        .reading(DeviceInfo.self),
        .stream(ThermalState.self),
        .stream(CameraSessionState.self),
        .stream(ViewControllerAppear.self),
        .stream(ViewLayoutPass.self),
        .stream(TaskMetrics.self),
        .stream(PathTransitions.self),
        .stream(AppState.self),
        .stream(CameraDeviceInventory.self),
        .stream(CameraSessionConfiguration.self),
        .stream(CameraDeviceFormat.self),
        .stream(CameraFrameDelivery.self),
        .stream(MainThreadHang.self),
        .fault(ThreadSnapshot.self),
        .stream(RuntimeIssues.self),
        .stream(HostAppear.self),
        .stream(HostUpdates.self),
        .stream(Presentation.self),
        .stream(DisplayListChurn.self),
        .stream(MemoryPressure.self),
        .reading(PermissionStatus.self),
        .stream(PermissionChanges.self),
        .stream(LastRunEnded.self),
        .reading(ThreadInventoryReading.self),
        .stream(QueueLatency.self),
        .stream(ThreadCPUUsage.self),
        .stream(Wakeups.self),
        .stream(CoreDataSave.self),
        .stream(CoreDataChanges.self),
        .stream(LogFaults.self),
        .stream(LogSubsystems.self),
        .stream(SessionConfiguration.self),
        .reading(TransportSecurity.self),
        .stream(FramePacing.self),
        .stream(AccessibilityFlags.self),
        .stream(DynamicType.self),
        .reading(LocaleSettings.self),
        .stream(CloudKitEvents.self),
        .stream(KeyValueStoreSync.self),
        .stream(NotificationSettings.self),
        .stream(DelegateSilence.self),
        .stream(CentralState.self),
        .stream(ContentProcessTermination.self),
        .stream(TileLoading.self),
        .stream(ProviderActions.self),
    ]

    public static func named(_ name: String) -> Registration? {
        all.first { $0.name == name }
    }
}
