public enum Instruments {
    public static let all: [Registration] = [
        .reading(MemoryFootprint.self, entity: .process),
        .reading(DeviceInfo.self, entity: .device),
        .stream(ThermalState.self, entity: .thermal),
        .stream(CameraSessionState.self, entity: .captureSession),
        .stream(ViewControllerAppear.self, entity: .screen),
        .stream(ViewLayoutPass.self, entity: .viewLayout),
        .stream(TaskMetrics.self, entity: .networkTask),
        .stream(PathTransitions.self, entity: .networkPath),
        .stream(AppState.self, entity: .appLifecycle),
        .stream(CameraDeviceInventory.self, entity: .captureDevice),
        .stream(CameraSessionConfiguration.self, entity: .captureSession),
        .stream(CameraDeviceFormat.self, entity: .captureDevice),
        .stream(CameraFrameDelivery.self, entity: .videoFrames),
        .stream(MainThreadHang.self, entity: .mainThread),
        .fault(ThreadSnapshot.self, entity: .thread),
        .stream(RuntimeIssues.self, entity: .swiftUIRuntimeIssue),
        .stream(HostAppear.self, entity: .swiftUIHost),
        .stream(HostUpdates.self, entity: .swiftUIHost),
        .stream(Presentation.self, entity: .swiftUIPresentation),
        .stream(DisplayListChurn.self, entity: .swiftUIDisplayList),
        .stream(MemoryPressure.self, entity: .memoryPressure),
        .reading(PermissionStatus.self, entity: .permission),
        .stream(PermissionChanges.self, entity: .permission),
        .stream(LastRunEnded.self, entity: .appExit),
        .reading(ThreadInventoryReading.self, entity: .thread),
        .stream(QueueLatency.self, entity: .dispatchQueue),
        .stream(ThreadCPUUsage.self, entity: .thread),
        .stream(Wakeups.self, entity: .process),
        .stream(CoreDataSave.self, entity: .managedObjectContext),
        .stream(CoreDataChanges.self, entity: .managedObjectContext),
        .stream(LogFaults.self, entity: .logRecord),
        .stream(LogSubsystems.self, entity: .logRecord),
        .stream(SessionConfiguration.self, entity: .networkSession),
        .reading(TransportSecurity.self, entity: .transportSecurity),
        .stream(FramePacing.self, entity: .displayUpdate),
        .stream(AccessibilityFlags.self, entity: .deviceSetting),
        .stream(DynamicType.self, entity: .deviceSetting),
        .reading(LocaleSettings.self, entity: .deviceSetting),
        .stream(NotificationSettings.self, entity: .notificationSetting),
        .stream(DelegateSilence.self, entity: .locationDelegate),
        .stream(CentralState.self, entity: .bluetoothCentral),
        .stream(ContentProcessTermination.self, entity: .webView),
        .stream(TileLoading.self, entity: .mapView),
        .stream(ProviderActions.self, entity: .callProvider),
        .stream(AudioRoute.self, entity: .audioRoute),
        .stream(StackSamples.self, entity: .stackSample),
        .stream(DrawablePresentation.self, entity: .metalDrawable),
        .stream(GPULatency.self, entity: .gpu),
        .reading(LinkedLibraries.self, entity: .binaryImage),
        .reading(MethodOwners.self, entity: .method),
        .stream(WindowTouches.self, entity: .touches),
        .stream(ControlAction.self, entity: .controlAction),
        .stream(GestureState.self, entity: .gestureRecognizer),
        .reading(ViewHierarchy.self, entity: .viewHierarchy),
        .stream(ImagingRenderPasses.self, entity: .imageRender),
    ]

    public static func named(_ name: String) -> Registration? {
        all.first { $0.name == name }
    }
}
