/// What a component's value *does*, not what type it's stored as — an index is not a quantity.
public enum ComponentRole: Equatable, Sendable {
    /// A magnitude. Comparable, summable, worth a line and a peak.
    case quantity
    /// Changes and is worth seeing change, but has no size: strings, flags, codes, indices.
    case state
    /// An id that ties readings together rather than describing one.
    case correlation
}

public extension Component.ID {
    var role: ComponentRole {
        switch self {
        case .activeConnectionCount,
             .activeTouchCount,
             .audioOutputCount,
             .availableInputCount,
             .bundledImageCount,
             .bytesReceivedCount,
             .bytesSentCount,
             .callbackCount,
             .connectionCount,
             .connectNanoseconds,
             .contentProcessTerminations,
             .cpuNanoseconds,
             .cpuUsageRatio,
             .deadlineMissCount,
             .deadlineOverrunNanoseconds,
             .delegateDurationNanoseconds,
             .delegateDurationPeakNanoseconds,
             .deletedCount,
             .displayListChangeCount,
             .displayListItemCount,
             .dnsNanoseconds,
             .dragDistancePoints,
             .drawableRequestCount,
             .drawableSkippedCount,
             .drawableUnavailableCount,
             .emptyResultCount,
             .formatCount,
             .formatHeightPixels,
             .formatMaxFramesPerSecond,
             .formatMinFramesPerSecond,
             .formatWidthPixels,
             .fps,
             .frameBudgetNanoseconds,
             .frameHeightPoints,
             .framesDeliveredCount,
             .framesDroppedCount,
             .frameWidthPoints,
             .gpuExecutionNanoseconds,
             .gpuExecutionPeakNanoseconds,
             .gpuWaitNanoseconds,
             .gpuWaitPeakNanoseconds,
             .hangNanoseconds,
             .hardwareCostRatio,
             .hostAppearNanoseconds,
             .hostCount,
             .idleWakeupCount,
             .imageTextBytes,
             .inputCount,
             .insertedCount,
             .mapLoadsCompleted,
             .maximumConnectionsPerHost,
             .maximumSimultaneousTouchCount,
             .memoryAvailableBytes,
             .memoryLimitBytes,
             .memoryUsedBytes,
             .methodDurationMilliseconds,
             .occurrenceCount,
             .outputCount,
             .outputVolume,
             .overBudgetCount,
             .passCount,
             .peakNanoseconds,
             .presentationLatencyNanoseconds,
             .queueLatencyNanoseconds,
             .refreshedCount,
             .requestTimeoutSeconds,
             .resourceTimeoutSeconds,
             .responseNanoseconds,
             .retiredChangedKeyCount,
             .retiredLayoutMaxDuration,
             .retiredLayoutTotalDuration,
             .runLoopTurnCount,
             .sampleCount,
             .serverNanoseconds,
             .silenceNanoseconds,
             .systemPressureCostRatio,
             .textureBackedImageCount,
             .tileLoadFailures,
             .tlsNanoseconds,
             .totalNanoseconds,
             .touchesMovedCount,
             .transactionCount,
             .unwindFailureCount,
             .updatedCount,
             .videoRotationDegrees,
             .wakeupCount,
             .windowNanoseconds:
            .quantity

        // Opaque and meaningless as a value, but its growth rate is the signal reported.
        case .displayListSeed:
            .quantity

        case .deviceId,
             .deviceUniqueId,
             .faultId,
             .instanceId,
             .instrument,
             .launchId,
             .threadIdentifier,
             .touchId,
             .userId,
             .viewId,
             .viewParent:
            .correlation

        // Numbers that aren't quantities: addresses, an index, an error code spelled in digits.
        case .errorCode,
             .frameAddress,
             .httpStatusCode,
             .imageLoadAddress,
             .multiCamSetIndex,
             .retiredInstrumentVersion,
             .retiredSyncEventType,
             .threadBasePriority,
             .threadIndex,
             .threadPriority:
            .state

        // A wall-clock instant; charted, it would draw a line whose slope is the passage of time.
        case .bootTimeMicroseconds,
             .intervalEndMicroseconds:
            .state

        case .accuracyClass,
             .activeColorSpace,
             .alertStyle,
             .appState,
             .appVersion,
             .audioCategory,
             .audioCategoryOptions,
             .audioInputDataSource,
             .audioInputName,
             .audioInputOrientation,
             .audioInputPolarPattern,
             .audioInputPort,
             .audioInputVerdict,
             .audioMode,
             .audioOutputName,
             .audioOutputPort,
             .audioPreviousOutputPort,
             .audioRouteVerdict,
             .authorizationStatus,
             .bluetoothState,
             .buildConfiguration,
             .buildUUID,
             .bundleId,
             .cachePolicy,
             .calendarIdentifier,
             .callAction,
             .changeReason,
             .contextConcurrency,
             .debuggerAttached,
             .delegateClass,
             .detail,
             .deviceKind,
             .deviceModel,
             .devicePosition,
             .deviceType,
             .dnsProtocol,
             .dropReason,
             .errorDomain,
             .exceptionDomain,
             .exitReason,
             .formatPixelFormat,
             .gestureRecognizerState,
             .hostKind,
             .hostNavigationTitle,
             .hostRootViewType,
             .hostViewClass,
             .imageName,
             .imageUUID,
             .interfaceKind,
             .interfaceOrientation,
             .ivarPathGeneration,
             .languageCode,
             .layoutDirection,
             .logCategory,
             .logLevel,
             .logMessage,
             .logSubsystem,
             .mechanismStatus,
             .memoryPressureLevel,
             .memoryPressureScope,
             .methodClass,
             .methodName,
             .minimumTLSVersion,
             .multiCamSetMembers,
             .negotiatedProtocol,
             .nestedLevel,
             .notificationSetting,
             .originXPoints,
             .originYPoints,
             .osVersion,
             .outputPixelFormat,
             .permissionSubject,
             .presentationKind,
             .presentedRootViewType,
             .previewVisibility,
             .queueLabel,
             .regionCode,
             .remoteAddress,
             .renderDestination,
             .requestURL,
             .retiredActiveInstrument,
             .runtimeClassName,
             .sdkVersion,
             .serverVersion,
             .sessionClass,
             .sessionPreset,
             .settingName,
             .settingState,
             .source,
             .systemPressureLevel,
             .textSizeCategory,
             .thermalState,
             .threadName,
             .threadRequestedQos,
             .threadRunState,
             .tlsCipherSuite,
             .tlsVersion,
             .touchPhase,
             .unsatisfiedReason,
             .viewControllerClass:
            .state

        case .accessibilityTextSize,
             .allowsCellular,
             .allowsConstrained,
             .allowsExpensive,
             .arbitraryLoadsAllowed,
             .audioInputAvailable,
             .audioPreferredInputHonored,
             .callbackImplemented,
             .confinementViolation,
             .connectionReused,
             .constrainedInterface,
             .expensiveInterface,
             .formatMultiCamSupported,
             .hangResolved,
             .hostRootViewOpaque,
             .implementationInMappedImage,
             .insecureLoadsAllowed,
             .multipath,
             .otherAudioPlaying,
             .outputPixelFormatSupported,
             .ownedByDeclaringImage,
             .pathSatisfied,
             .proxyConnection,
             .retiredSyncSucceeded,
             .secondaryAudioSilenced,
             .sessionInterrupted,
             .sessionRunning,
             .settingEnabled,
             .threadIdle,
             .threadIsMain,
             .usageDescriptionDeclared,
             .uses24HourTime,
             .usesMetricSystem,
             .videoMirrored,
             .waitsForConnectivity:
            .state
        }
    }
}
