/// The words a person reads for each component. No code on the device consults these.
public extension Component.ID {
    var label: String {
        switch self {
        case .cpuUsageRatio: "CPU"
        case .fps: "FPS"
        case .deviceId: "Device ID"
        case .source: "Source"
        case .methodName: "Method"
        case .methodDurationMilliseconds: "Duration (ms)"
        case .deviceModel: "Device"
        case .osVersion: "OS"
        case .appVersion: "App version"
        case .userId: "User"
        case .serverVersion: "Server version"
        case .memoryUsedBytes: "Memory (bytes)"
        case .thermalState: "Thermal"
        case .detail: "Detail"
        case .instrument: "Instrument"
        case .retiredInstrumentVersion: "Instrument version (retired)"
        case .retiredLayoutTotalDuration: "Time in layout, milliseconds (retired)"
        case .retiredLayoutMaxDuration: "Slowest layout pass, milliseconds (retired)"
        case .bundleId: "Bundle"
        case .buildConfiguration: "Build"
        case .deviceKind: "Running on"
        case .sdkVersion: "SDK version"
        case .appName: "App name"
        case .reuseIdentifier: "Reuse identifier"
        case .sectionIndex: "Section"
        case .itemIndex: "Item"
        case .memoryUsageRatio: "Memory (of limit)"
        case .systemFreeBytes: "System free (bytes)"
        case .systemFreeRatio: "System free (of physical)"
        case .memoryTag: "Memory owner"
        case .residentBytes: "Resident (bytes)"
        case .dirtyBytes: "Dirty (bytes)"
        case .compressedBytes: "Compressed (bytes)"
        case .regionCount: "Regions"
        case .dirtyDeltaBytes: "Dirty change (bytes)"
        case .appearedCount: "Appeared"
        case .appearedBytes: "Appeared (bytes)"
        case .vanishedCount: "Vanished"
        case .vanishedBytes: "Vanished (bytes)"
        case .imageSource: "Image source"
        case .imageData: "Image"
        case .imageFormat: "Image format"
        case .screenScale: "Screen scale"
        case .passCount: "Passes"
        case .totalNanoseconds: "Total (ns)"
        case .peakNanoseconds: "Slowest (ns)"
        case .sessionRunning: "Session running"
        case .sessionInterrupted: "Session interrupted"
        case .viewControllerClass: "View controller"
        case .instanceId: "Instance"
        case .httpStatusCode: "HTTP status"
        case .negotiatedProtocol: "Protocol"
        case .bytesSentCount: "Sent (bytes)"
        case .bytesReceivedCount: "Received (bytes)"
        case .requestURL: "URL"
        case .connectionReused: "Connection reused"
        case .interfaceKind: "Interface"
        case .pathSatisfied: "Path satisfied"
        case .expensiveInterface: "Expensive"
        case .constrainedInterface: "Constrained"
        case .unsatisfiedReason: "Why not satisfied"
        case .errorDomain: "Error domain"
        case .errorCode: "Error code"
        case .appState: "App state"
        case .sessionClass: "Session class"
        case .sessionPreset: "Preset"
        case .inputCount: "Inputs"
        case .outputCount: "Outputs"
        case .connectionCount: "Connections"
        case .activeConnectionCount: "Connections carrying"
        case .hardwareCostRatio: "Hardware cost"
        case .systemPressureCostRatio: "System pressure cost"
        case .systemPressureLevel: "System pressure"
        case .deviceType: "Camera"
        case .devicePosition: "Facing"
        case .deviceUniqueId: "Camera ID"
        case .formatWidthPixels: "Width"
        case .formatHeightPixels: "Height"
        case .formatPixelFormat: "Pixel format"
        case .formatMinFramesPerSecond: "Min FPS"
        case .formatMaxFramesPerSecond: "Max FPS"
        case .formatMultiCamSupported: "Multi-camera capable"
        case .formatCount: "Formats available"
        case .activeColorSpace: "Colour space"
        case .videoRotationDegrees: "Rotation"
        case .videoMirrored: "Mirrored"
        case .multiCamSetIndex: "Set"
        case .multiCamSetMembers: "Cameras in set"
        case .outputPixelFormat: "Output pixel format"
        case .outputPixelFormatSupported: "Output format deliverable"
        case .framesDeliveredCount: "Frames delivered"
        case .framesDroppedCount: "Frames dropped"
        case .dropReason: "Why dropped"
        case .delegateDurationNanoseconds: "Delegate duration (ns)"
        case .delegateDurationPeakNanoseconds: "Longest delegate duration (ns)"
        case .hangNanoseconds: "Hang duration (ns)"
        case .hangResolved: "Hang recovered"
        case .runLoopTurnCount: "Run loop turns"
        case .threadIndex: "Thread"
        case .threadName: "Thread name"
        case .threadIsMain: "Main thread"
        case .frameAddress: "Frame"
        case .imageName: "Binary"
        case .imageLoadAddress: "Loaded at"
        case .imageUUID: "Binary UUID"
        case .buildUUID: "Build UUID"
        case .launchId: "Launch"
        case .logSubsystem: "Log subsystem"
        case .logCategory: "Log category"
        case .logMessage: "Message"
        case .occurrenceCount: "Times"
        case .hostRootViewType: "Root view"
        case .hostRootViewOpaque: "Root view erased"
        case .hostNavigationTitle: "Screen title"
        case .hostAppearNanoseconds: "Time to appear (ns)"
        case .hostKind: "Host kind"
        case .hostCount: "Hosts alive"
        case .hostViewClass: "Hosting view class"
        case .mechanismStatus: "Mechanism"
        case .displayListSeed: "Display list seed"
        case .displayListItemCount: "Display list items"
        case .displayListChangeCount: "Display list changes"
        case .ivarPathGeneration: "Renderer path"
        case .presentationKind: "Presentation style"
        case .presentedRootViewType: "Presented view"
        case .windowNanoseconds: "Window (ns)"
        case .memoryLimitBytes: "Memory limit (bytes)"
        case .memoryAvailableBytes: "Memory headroom (bytes)"
        case .memoryPressureLevel: "Memory pressure"
        case .memoryPressureScope: "Pressure reported for"
        case .exitReason: "Exit reason"
        case .intervalEndMicroseconds: "Measured through"
        case .bootTimeMicroseconds: "Booted at"
        case .permissionSubject: "Permission"
        case .authorizationStatus: "Authorization"
        case .usageDescriptionDeclared: "Usage description shipped"
        case .threadIdentifier: "Thread ID"
        case .threadRunState: "Thread state"
        case .threadRequestedQos: "Requested QoS"
        case .threadIdle: "Idle thread"
        case .threadPriority: "Priority"
        case .threadBasePriority: "Base priority"
        case .cpuNanoseconds: "CPU (ns)"
        case .wakeupCount: "Wakeups"
        case .idleWakeupCount: "Idle wakeups"
        case .queueLatencyNanoseconds: "Queue wait (ns)"
        case .queueLabel: "Queue"
        case .insertedCount: "Inserted"
        case .updatedCount: "Updated"
        case .deletedCount: "Deleted"
        case .refreshedCount: "Refreshed"
        case .contextConcurrency: "Context queue"
        case .confinementViolation: "Used off its own queue"
        case .logLevel: "Level"
        case .dnsNanoseconds: "DNS (ns)"
        case .connectNanoseconds: "Connect (ns)"
        case .tlsNanoseconds: "TLS handshake (ns)"
        case .serverNanoseconds: "Server think (ns)"
        case .responseNanoseconds: "Download (ns)"
        case .tlsVersion: "TLS version"
        case .tlsCipherSuite: "Cipher suite"
        case .transactionCount: "Transactions"
        case .requestTimeoutSeconds: "Request timeout (s)"
        case .resourceTimeoutSeconds: "Resource timeout (s)"
        case .allowsCellular: "Cellular allowed"
        case .allowsExpensive: "Expensive networks allowed"
        case .allowsConstrained: "Constrained networks allowed"
        case .waitsForConnectivity: "Waits for connectivity"
        case .maximumConnectionsPerHost: "Max connections per host"
        case .cachePolicy: "Cache policy"
        case .dnsProtocol: "DNS protocol"
        case .remoteAddress: "Served by"
        case .proxyConnection: "Through a proxy"
        case .multipath: "Multipath"
        case .arbitraryLoadsAllowed: "Arbitrary loads allowed"
        case .exceptionDomain: "ATS exception domain"
        case .insecureLoadsAllowed: "Plain http allowed"
        case .minimumTLSVersion: "Minimum TLS"
        case .deadlineMissCount: "Frames past deadline"
        case .deadlineOverrunNanoseconds: "Worst overrun (ns)"
        case .presentationLatencyNanoseconds: "Presentation latency (ns)"
        case .settingName: "Setting"
        case .settingEnabled: "Turned on"
        case .textSizeCategory: "Text size"
        case .accessibilityTextSize: "Accessibility text size"
        case .languageCode: "Language"
        case .regionCode: "Region"
        case .calendarIdentifier: "Calendar"
        case .usesMetricSystem: "Metric"
        case .uses24HourTime: "24-hour time"
        case .layoutDirection: "Layout direction"
        case .changeReason: "Change reason"
        case .retiredSyncEventType: "Sync event (retired)"
        case .retiredSyncSucceeded: "Sync succeeded (retired)"
        case .retiredChangedKeyCount: "Keys changed (retired)"
        case .notificationSetting: "Notification setting"
        case .settingState: "State"
        case .alertStyle: "Alert style"
        case .previewVisibility: "Previews"
        case .callbackImplemented: "Callback implemented"
        case .silenceNanoseconds: "Waited (ns)"
        case .accuracyClass: "Accuracy asked for"
        case .callbackCount: "Callbacks"
        case .delegateClass: "Delegate"
        case .bluetoothState: "Bluetooth state"
        case .contentProcessTerminations: "Content process deaths"
        case .tileLoadFailures: "Map load failures"
        case .mapLoadsCompleted: "Map loads completed"
        case .callAction: "Call action"
        case .audioOutputPort: "Output port"
        case .audioOutputName: "Output name"
        case .audioInputPort: "Input port"
        case .audioCategory: "Audio category"
        case .audioMode: "Audio mode"
        case .audioCategoryOptions: "Category options"
        case .audioPreviousOutputPort: "Previous output port"
        case .audioRouteVerdict: "Where the audio is going"
        case .audioInputVerdict: "What is listening"
        case .audioInputName: "Input name"
        case .audioInputDataSource: "Microphone"
        case .audioInputPolarPattern: "Pickup pattern"
        case .audioInputOrientation: "Microphone orientation"
        case .audioInputAvailable: "Input available"
        case .audioPreferredInputHonored: "Preferred input honored"
        case .availableInputCount: "Inputs available"
        case .audioOutputCount: "Outputs in route"
        case .outputVolume: "Output volume"
        case .otherAudioPlaying: "Other audio playing"
        case .secondaryAudioSilenced: "Secondary audio silenced"
        case .sampleCount: "Samples taken"
        case .unwindFailureCount: "Samples with no stack"
        case .drawableRequestCount: "Drawables requested"
        case .drawableSkippedCount: "Frames skipped"
        case .drawableUnavailableCount: "Drawables unavailable"
        case .gpuWaitNanoseconds: "GPU wait (ns)"
        case .gpuWaitPeakNanoseconds: "Longest GPU wait (ns)"
        case .gpuExecutionNanoseconds: "GPU execution (ns)"
        case .gpuExecutionPeakNanoseconds: "Longest GPU execution (ns)"
        case .frameBudgetNanoseconds: "Frame budget (ns)"
        case .overBudgetCount: "Probes over budget"
        case .imageTextBytes: "Code size (bytes)"
        case .bundledImageCount: "Shipped with the app"
        case .methodClass: "Class"
        case .ownedByDeclaringImage: "In declaring image"
        case .implementationInMappedImage: "In a mapped image"
        case .touchPhase: "Touch phase"
        case .activeTouchCount: "Fingers down"
        case .touchesMovedCount: "Touch moves"
        case .dragDistancePoints: "Drag distance (pt)"
        case .maximumSimultaneousTouchCount: "Most fingers at once"
        case .touchId: "Touch id"
        case .originXPoints: "X (pt)"
        case .originYPoints: "Y (pt)"
        case .frameWidthPoints: "Width (pt)"
        case .frameHeightPoints: "Height (pt)"
        case .runtimeClassName: "Runtime class"
        case .gestureRecognizerState: "Gesture state"
        case .viewId: "View ID"
        case .viewParent: "Parent view"
        case .nestedLevel: "Nesting depth"
        case .faultId: "Fault ID"
        case .renderDestination: "Renders into"
        case .textureBackedImageCount: "Images from a texture"
        case .emptyResultCount: "Produced nothing"
        case .debuggerAttached: "Debugger attached"
        case .interfaceOrientation: "Orientation"
        case .retiredActiveInstrument: "Now running (retired)"
        }
    }
}
